import Foundation
import SQLite3

/// Pinyin → Chinese character / phrase lookup backed by a bundled SQLite database.
/// Database generated by scripts/generate_pinyin_db.py from Google PinyinIME rawdict (Apache 2.0).
enum PinyinEngine {

    // MARK: - Public API

    /// Per-syllable candidates for the given buffer (used by the candidate strip).
    /// Result ordering: phrase-exact > single-exact > phrase-prefix > single-prefix.
    static func candidates(for buffer: String, traditional: Bool) -> [String] {
        guard !buffer.isEmpty, let db else { return [] }
        return queryCandidates(db: db, buffer: buffer,
                               script: traditional ? "hant" : "hans")
    }

    /// Assembles the most likely sentence for a multi-syllable buffer.
    /// Segments the buffer, then greedily picks the best phrase for each
    /// 4 / 3 / 2 / 1 syllable span.
    /// Returns nil when the buffer is too short (< 2 recognisable syllables).
    static func assembledSentence(for buffer: String, traditional: Bool) -> String? {
        guard let db else { return nil }
        let script = traditional ? "hant" : "hans"
        let segs = PinyinSegmenter.segment(buffer)
        // Need at least 2 complete syllables
        let completeSyllables = segs.filter { PinyinSegmenter.validSyllables.contains($0) }
        guard completeSyllables.count >= 2 else { return nil }

        var result = ""
        var i = 0
        while i < completeSyllables.count {
            var found = false
            for span in [4, 3, 2, 1] where i + span <= completeSyllables.count {
                let key = completeSyllables[i..<(i + span)].joined()
                if let top = topExact(db: db, syllable: key, script: script) {
                    result += top
                    i += span
                    found = true
                    break
                }
            }
            if !found { i += 1 }
        }
        return result.isEmpty ? nil : result
    }

    // MARK: - Database handle (opened once, read-only)

    private static let db: OpaquePointer? = {
        guard let url = Bundle.main.url(forResource: "pinyin", withExtension: "db") else {
            return nil
        }
        var handle: OpaquePointer?
        let flags = SQLITE_OPEN_READONLY | SQLITE_OPEN_FULLMUTEX
        guard sqlite3_open_v2(url.path, &handle, flags, nil) == SQLITE_OK else {
            return nil
        }
        return handle
    }()

    private static let transient = unsafeBitCast(-1, to: sqlite3_destructor_type.self)

    // MARK: - Per-syllable candidate query (exact + prefix, phrases first)

    private static func queryCandidates(db: OpaquePointer,
                                        buffer: String,
                                        script: String) -> [String] {
        let sql = """
            SELECT character FROM candidates
            WHERE syllable LIKE ? AND script = ?
            ORDER BY
                CASE
                    WHEN LENGTH(character) > 1 AND syllable = ? THEN 0
                    WHEN LENGTH(character) = 1 AND syllable = ? THEN 1
                    WHEN LENGTH(character) > 1               THEN 2
                    ELSE                                           3
                END,
                frequency ASC
            LIMIT 40
        """
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else { return [] }
        defer { sqlite3_finalize(stmt) }

        sqlite3_bind_text(stmt, 1, buffer + "%", -1, transient)
        sqlite3_bind_text(stmt, 2, script,       -1, transient)
        sqlite3_bind_text(stmt, 3, buffer,       -1, transient)
        sqlite3_bind_text(stmt, 4, buffer,       -1, transient)

        var results: [String] = []
        var seen = Set<String>()
        while sqlite3_step(stmt) == SQLITE_ROW {
            if let cStr = sqlite3_column_text(stmt, 0) {
                let s = String(cString: cStr)
                if seen.insert(s).inserted { results.append(s) }
            }
        }
        return results
    }

    // MARK: - Single best-match query for sentence assembly

    private static func topExact(db: OpaquePointer,
                                 syllable: String,
                                 script: String) -> String? {
        let sql = """
            SELECT character FROM candidates
            WHERE syllable = ? AND script = ?
            ORDER BY frequency ASC
            LIMIT 1
        """
        var stmt: OpaquePointer?
        guard sqlite3_prepare_v2(db, sql, -1, &stmt, nil) == SQLITE_OK else { return nil }
        defer { sqlite3_finalize(stmt) }

        sqlite3_bind_text(stmt, 1, syllable, -1, transient)
        sqlite3_bind_text(stmt, 2, script,   -1, transient)

        guard sqlite3_step(stmt) == SQLITE_ROW,
              let cStr = sqlite3_column_text(stmt, 0) else { return nil }
        return String(cString: cStr)
    }
}
